table 'Min Bill Amount'
	lineageTag: d2b4f13e-465f-4b4b-897c-c3c36c3afd8c

	measure 'Min Bill Amount Value' = SELECTEDVALUE('Min Bill Amount'[Min Bill Amount])
		formatString: 0
		lineageTag: a9788d99-d804-4d7d-9922-2a9435c71e5c

	column 'Min Bill Amount'
		formatString: 0
		lineageTag: ce7b03ab-094c-4ff1-ada5-6465458e75a9
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Min Bill Amount]

		annotation SummarizationSetBy = Automatic

	partition 'Min Bill Amount' = calculated
		mode: import
		source = ```
				
				DATATABLE(
				    "Min Bill Amount", INTEGER,
				    {
				        {0},
				        {5000},
				        {15000},
				        {25000},
				        {35000},
				        {50000},
				        {70000},
				        {100000},
				        {150000},
				        {200000},
				        {250000}
				    }
				)
				
				```

	annotation PBI_Id = 912e7edd7ca74c22886d217f6f8ba50b

